# Generated by Django 4.1.3 on 2023-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='achievement_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description',
            field=models.TextField(default='No description', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='No email', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
