# Generated by Django 4.2 on 2023-04-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_achievement_achievement_id_achievement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='achievements',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='achievements.achievement'),
        ),
    ]
