# Generated by Django 4.2 on 2023-04-17 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_student_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='achievements.student'),
        ),
    ]
