# Generated by Django 4.2 on 2023-04-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_remove_student_achievements_achievement_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='achievement',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='achievements.achievement'),
        ),
    ]
