# Generated by Django 4.2 on 2023-04-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0005_remove_achievement_student_student_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='achievement',
        ),
        migrations.AddField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='achievements.student'),
        ),
    ]
